### ISSUE TITLE
Initialize a nodejs server with minimal requirements.

### ISSUE THREAD

**Issue by recurrenc** [NetScape-Web/hacktoberfest-express-server-2022#1]
Initialize a nodejs server with minimal requirements.

**STEPS**

> Install [Node](https://nodejs.org/en/) in your local system

**check if it is successfully installed and added to the path of your system variables.** 

> open cmd/terminal and run `node --version`.
![image](https://user-images.githubusercontent.com/45717030/193421275-aaa63327-149a-4b74-bc18-2dd6a9a8c2be.png)

> clone this repository and open it in terminal.

> initialize npm project by command `npm init`

> Read about [express js](https://expressjs.com/en/starter/hello-world.html) and create basic express server

**Comment by 0xsonu** [comment]
@recurrenc Please Assign this isue to me~
