### ISSUE TITLE
Create A connection between MongoDB Local Instance and Express Server.

### ISSUE THREAD

**Issue by recurrenc** [NetScape-Web/hacktoberfest-express-server-2022#2]
Install Following packages 

1. mongoose
2. dotenv

Go To [MongoDB official Documentation](https://www.mongodb.com/docs/) and [Mongoose Official Documentation](https://mongoosejs.com/docs/guide.html) for reference.

Connect mongodb to our server.

**Comment by 0xsonu** [comment]
@recurrenc I want to work on this issue. Please assign it to me.

**Comment by recurrenc** [comment]
resolved by #8
